### ISSUE TITLE
マップの地形を作成

### ISSUE THREAD

**Issue by rind0** [yurikazuna929/ElementTD#2]
- [x] Sceneを「Stage1」として作成する
- [ ] Terrainを使って以下の様な地形を作成する
  キャラのサイズを 0.5 m \* 0.5 m \* 1 m(高さ) として
  - 緑色は山で、移動不能(山の高さは最大10 m)
    - カメラ角60 °でも見えないところがないように
  - 土色は道、移動可能
  - マップサイズはX=50 m, Z=30 m
    ![stage1](https://cloud.githubusercontent.com/assets/11273198/13838065/4584270a-ec54-11e5-8a8e-a92a81145076.png)
- [x] 魔法陣はアセットストアからかっこいいのを拾ってきましょう
- [x] 地形と魔法陣を空のオブジェクト「Map」に入れて静的オブジェクトとしておく

**Comment by Iruyan-Zak** [comment]
Terrainの色(テクスチャ)付けは別issue立てます。
